debug: true
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: TIS-REVALIDAITON-CONCERNS

server:
  servlet:
    context-path: /revalidation
  port: ${SERVICE_PORT:8087}
