debug: true
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: tis-revalidation-concerns

server:
  servlet:
    context-path: /concerns
  port: ${SERVICE_PORT:8087}

app:
  concern:
    revalidation:
      url: ${REVALIDATION_URL:http://localhost:8080/revalidation/api}
