debug: true
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: tis-revalidation-concerns
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:root}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:revalidation}?authSource=admin&authMechanism=SCRAM-SHA-1

server:
  servlet:
    context-path: /concerns
  port: ${SERVICE_PORT:8087}

app:
  cognito:
    admin-group: ${ADMIN_GROUP}
    admin-user-pool: ${ADMIN_USER_POOL}
  concern:
    revalidation:
      url: ${REVALIDATION_URL:http://localhost:8080/revalidation/api}
